name: Summary

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - edited

jobs:
  summary-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: .github/test/package-lock.json
      - run: npm install --prefix .github/test
      - run: npm test --prefix .github/test

      - uses: pascalgn/automerge-action@v0.14.3
        env:
          MERGE_LABELS: ""
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@0c4b27844ba47cb1c7bee539c8eead5284ce9fa9
        with:
          args: 'The summary of ${{github.event.pull_request.head.repo.full_name }} has been accepted.'
